/*=========================================================
*Copyright(c) 2017 CyberLogitec. All Rights Reserved.
*@FileName 	 : COM_ENS_0X1.js
*@FileTitle  : CSR amount limitation setup
*@author     : CLT
*@version    : 1.0
*@since      : 2017/10/10
=========================================================*/
// common global variables 
var sheetObjects=new Array();
var sheetCnt=0;
var comboObjects = new Array();
var comboCnt = 0;

var g_rhq_ofc_cd="";
var g_ofc_cd="";
var g_sub_sys_cd="";
var g_setting = false;
// Event handler processing by button click event*/
document.onclick=processButtonClick;
// Event handler processing by button name */
function processButtonClick(){
 var sheetObject=sheetObjects[0];
 var importSheetObject=sheetObjects[1];
 var formObject=document.form;	
	try {
		var srcName=ComGetEvent("name");
		if(ComGetBtnDisable(srcName)) return false;
		switch(srcName) {
			case "btn_retrieve":
	         	doActionIBSheet(sheetObject,formObject,IBSEARCH);
	        break;
			case "btn_new":
				resetAll();
			break;
			case "btn_save":
				if (ComShowCodeConfirm("COM12152", "CSR amount limitation")) {
					if(!isValidate(sheetObject)) return false;
					doActionIBSheet(sheetObject,formObject,IBSAVE);
				}
			break;
        } // end switch
	}catch(e) {
		if( e == "[object Error]") {
			ComShowMessage(OBJECT_ERROR);
		} else {
			ComShowMessage(e.message);
		}
	}
}
/**
 * registering IBSheet Object as list 
 * adding process for list in case of needing batch processing with other items
 * defining list on the top of source
 */
function setSheetObject(sheet_obj){
	sheetObjects[sheetCnt++]=sheet_obj;
}
/**
 * Registering IBMultiCombo Object generated on Page to comboObject Array <br>
 * comboObjects Array is defined on the top of source. This function is called automatically when IBMultiCombo Object is generated by {@link CoObject#ComComboObject} <br>
 * @param {ibmulticombo} combo_obj    IBMultiCombo Object
 **/
function setComboObject(combo_obj) {
	comboObjects[comboCnt++] = combo_obj;
}
/**
 * initializing sheet 
 * implementing onLoad event handler in body tag 
 * adding first-served functions after loading screen. 
 */
function loadPage() {
	var sheetObject=sheetObjects[0];
	var formObject=document.form;
	for(i=0;i<sheetObjects.length;i++){
	    ComConfigSheet (sheetObjects[i]);
	    initSheet(sheetObjects[i],i+1);
	    ComEndConfigSheet(sheetObjects[i]);
	}
	doActionIBSheet(sheetObject, formObject, IBSEARCH_ASYNC01);//RHQ.
}
/**
 * Loading Event of HTML_Control existing on page dynamically <br>
 * Calling the function from {@link #loadPage} to initialize IBSheet Object<br>
 * @param {ibsheet} sheetObj    IBSheet Object
 * @param {int}     sheetNo     sequence of sheetObjects array
 **/
function initControl() {
	axon_event.addListener  ('change', 'loc_cd_change', 'loc_cd');
	axon_event.addListener  ('change', 'act_flg_change', 'act_flg');
}

/**
 * setting sheet initial values and header <br>
 * adding case as numbers of counting sheets <br>
 * <br><b>Example :</b>
 * <pre>
 *     initSheet(sheetObj,1);
 * </pre>
 * @param {ibsheet} sheetObj Mandatory IBSheet Object
 * @param {int} sheetNo Mandatory IBSheet Object Tag's ID Serial No
 * @return N/A
 * @author 
 */
function initSheet(sheetObj,sheetNo) {
    var cnt=0;
    switch(sheetNo) {
        case 1:      //sheet1 init
            with(sheetObj){
	              var HeadTitle1="ibflag|No.|auth_yn|RHQ|Office|Module|Approval Limitation|Approval Limitation|1st Approver|1st Approver|2nd Approver|2nd Approver|Change History|1|2|3|4";
	              var HeadTitle2="ibflag|No.|auth_yn|RHQ|Office|Module|Currency|Amount(CSR)|Name|Office|Name|Office|Change History|1|2|3|4";
	              SetConfig( { SearchMode:0, MergeSheet:5, Page:20, DataRowMerge:0} );
	              var info    = { Sort:0, ColMove:1, HeaderCheck:0, ColResize:1 };
	              var headers = [ {Text:HeadTitle1, Align:"Center"},{Text:HeadTitle2, Align:"Center"} ];
	              InitHeaders(headers, info);
	              var cols = [
	                     {Type:"Status",Hidden:1, Width:30,  Align:"Center", ColMerge:0, SaveName:"ibflag" },
	                     {Type:"Seq",   Hidden:1, Width:50,  Align:"Center", ColMerge:0, SaveName:"seq",             KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:1, Width:100, Align:"Center", ColMerge:0, SaveName:"auth_yn",         KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:0, Width:100, Align:"Center", ColMerge:1, SaveName:"ar_hd_qtr_ofc_cd",KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:0, Width:100, Align:"Center", ColMerge:1, SaveName:"ofc_cd",          KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:0, Width:100, Align:"Center", ColMerge:0, SaveName:"sub_sys_cd",      KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Combo", Hidden:0, Width:100, Align:"Center", ColMerge:0, SaveName:"csr_curr_cd",     KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0, ComboText:"|USD|JPY",ComboCode:"|USD|JPY"},
	                     {Type:"Float", Hidden:0, Width:150, Align:"Right",  ColMerge:0, SaveName:"csr_amt",         KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0, PointCount:2, MaximumValue:99999999999999.99 },
	                     {Type:"Text",  Hidden:0, Width:210, Align:"Left",   ColMerge:0, SaveName:"apr_usr_nm_1st",  KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:0, Width:100, Align:"Center", ColMerge:0, SaveName:"apr_ofc_cd_1st",  KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:0, Width:210, Align:"Left",   ColMerge:0, SaveName:"apr_usr_nm_2nd",  KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:0, Width:100, Align:"Center", ColMerge:0, SaveName:"apr_ofc_cd_2nd",  KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Popup", Hidden:0, Width:200, Align:"Left",   ColMerge:0, SaveName:"history",         KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:1, InsertEdit:1 },
	                     {Type:"Text",  Hidden:1, Width:100, Align:"Center", ColMerge:0, SaveName:"apro_rout_seq",   KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:1, Width:50,  Align:"Center", ColMerge:0, SaveName:"dp_prcs_knt",     KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:1, Width:50,  Align:"Center", ColMerge:0, SaveName:"apr_usr_id_1st",  KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 },
	                     {Type:"Text",  Hidden:1, Width:50,  Align:"Center", ColMerge:0, SaveName:"apr_usr_id_2nd",  KeyField:0, CalcLogic:"", Format:"", PointCount:0, UpdateEdit:0, InsertEdit:0 }]
	              InitColumns(cols);
	              SetEditable(1);
	              resizeSheet();
                }
            break;
    }
}

// calling History Popup 
function sheet_OnPopupClick(sheetObj, Row, Col)
{
	var sub_sys_cd = sheetObj.GetCellValue(Row, "sub_sys_cd");
	var ofc_cd = sheetObj.GetCellValue(Row, "ofc_cd");
	var param="?sub_sys_cd="+sub_sys_cd+"&ofc_cd="+ofc_cd;
	ComOpenPopup("COM_ENS_0Z2.do"+param, 1000, 400, "", "1,0,1,1,1", true, false, 0, 0, 0, "COM_ENS_0Z2");
}

function sheet_OnChange(sheetObj, Row, Col, Value) {
	with(sheetObj) {
		if(ColSaveName(Col) == 'csr_curr_cd') {
			setAmtFormat(Value, Row);
		}
	}
}

/**
 * Handling IBSheet's process(Retrieve, Save) <br>
 * @param {ibsheet} sheetObj Mandatory IBSheet Object
 * @param {form}    formObj Mandatory html form object
 * @param {int}     sAction mandatory,Constant Variable
 * @param {string}  sCondFlg condition Flag
 **/
function doActionIBSheet(sheetObj,formObj,sAction,sCondFlg) {
    switch(sAction) {
    	case IBSEARCH:     //retrieve
			formObj.f_cmd.value=SEARCH;
			/*ComOpenWait(true);
            var sXml=sheetObj.GetSearchData("COM_ENS_0Z1GS.do", FormQueryString(formObj));
            sheetObj.LoadSearchData(sXml);
            ComOpenWait(false);*/
            sheetObj.DoSearch("COM_ENS_0Z1GS.do", FormQueryString(formObj));
    		break;
		case IBSAVE:       //save
			formObj.f_cmd.value=MULTI;
			var saveString = ComGetSaveString(sheetObj, true, true);//URI Encoding, AllSave
			sheetObj.DoAllSave("COM_ENS_0Z1GS.do", FormQueryString(formObj));
    	    break;
		case IBSEARCH_ASYNC01:				
    		formObj.f_cmd.value=SEARCH01;
			var sXml=sheetObj.GetSearchData("COM_ENS_0U2GS.do", FormQueryString(formObj));
			var sStr=ComGetEtcData(sXml,"rhq");
			var arrStr=sStr.split("|");
			var rhqOfcCd=ComGetEtcData(sXml,"rhq_ofc_cd");
			MakeComboObject(rhq_ofc_cd, arrStr, rhqOfcCd);
        break;
		case IBSEARCH_ASYNC02: // 화면 로딩시 Office 조회
			if(rhq_ofc_cd.GetSelectCode() == "SINHO") {
				ofc_cd.RemoveAll();
				ofc_cd.InsertItem(0, "SINHO", "SINHO");
			} else {
				formObj.f_cmd.value=SEARCH02;
				formObj.v_rhq_ofc_cd.value = rhq_ofc_cd.GetSelectCode();
				var sXml=sheetObj.GetSearchData("COM_ENS_0U2GS.do", FormQueryString(formObj));
				var aXml=sXml.split("|$$|");
				ComXml2ComboItem(aXml[0], ofc_cd, "ofc_cd","ofc_cd" ); 
			}
		 	with (ofc_cd) {
		 		SetMultiSelect(1);
		 		SetMultiSeparator(",");
		 		SetDropHeight(320);
		 	}
		 	ofc_cd.SetSelectCode(formObj.usr_ofc_cd.value);
		 	if(ofc_cd.GetSelectCode() == '') {
		 		ofc_cd.SetSelectCode(0);
		 	}
			if(sheetObj.RowCount()> 0)
	    		sheetObj.RemoveAll();
			//
			if(!g_setting) {
				g_rhq_ofc_cd=rhq_ofc_cd.GetSelectCode();
				g_ofc_cd=ofc_cd.GetSelectCode();
				g_sub_sys_cd=document.form.sub_sys_cd.value;
				g_setting = true;
			}
		break;
    }
}

/**
 * Validate Check<br>
 */
function isValidate(sheetObj) {
	with(sheetObj) {
		var start = HeaderRows();
		for(var i=start; i<start+RowCount(); i++) {
			if(GetCellValue(i, "csr_curr_cd") != "") {
				if(GetCellValue(i, "csr_amt") == "") {
					SelectCell(i, "csr_amt");
	            	alert("csr_amt");
	            	return false;
	            }
			}
			if(GetCellValue(i, "csr_amt") != "") {
	            if(GetCellValue(i, "csr_curr_cd") == "") {
	            	SelectCell(i, "csr_curr_cd");
	            	alert("csr_curr_cd");
	            	return false;
	            }
	            if(GetCellValue(i, "csr_amt") < 0) {
	            	alert("csr_curr_cd");
	            	return false;
	            }
	        }
	    }
	}
	return true;
}

function sheet_OnSaveEnd(sheetObj, Code, errMsg) {
    if (sheetObj.GetEtcData("TRANS_RESULT_KEY") == "S") {
    	ComShowCodeMessage("COM130102", "Data"); // {?msg1} was saved successfully.	
    	doActionIBSheet(sheetObj, document.form, IBSEARCH);
    }
}

function sheet_OnSearchEnd(sheetObj) {
	with(sheetObj) {
		var start = HeaderRows();
//		var tRhq = "";
//		var tOfcCd = "";
//		var mRhq = 0;
//		var mOfcCd = 0;
//		var iRhq = SaveNameCol("ar_hd_qtr_ofc_cd");
//		var iOfcCd = SaveNameCol("ofc_cd");
		for(var i=start; i<start+RowCount(); i++) {
			if(GetCellValue(i, "auth_yn") == "Y") {
	            SetCellEditable(i, "csr_curr_cd", 1);
				SetCellEditable(i, "csr_amt", 1);
	        }
			setAmtFormat(GetCellValue(i, "csr_curr_cd"), i);
	    }
		if(RowCount() > 0) {
			ComEnableObject(document.form.btn_save, true);
		} else {
			ComEnableObject(document.form.btn_save, false);
		}
	}
}

function setAmtFormat(csr_curr_cd, Row) {
//	with(sheetObj) {
//		var dp_prcs_knt = GetCellValue(row, "dp_prcs_knt");
//		var maximumValue = "99999999999999"; 
//		for(var j=0;j<pointCount;j++) {
//			if(j==0) {
//				maximumValue+=".9";
//			} else {
//				maximumValue+="9";
//			}
//		}
		var info = {Type:"Float", Align:"Right", Format:"NullFloat", PointCount:2, MaximumValue:99999999999999.99};
		if(csr_curr_cd == "JPY") {
			info = {Type:"Int", Align:"Right", Format:"NullInteger", PointCount:0, MaximumValue:99999999999999};
		} 
		sheetObjects[0].InitCellProperty(Row, "csr_amt", info);
//	}
}

function resizeSheet(){
    ComResizeSheet(sheetObjects[0]);
} 

/**
 * initial Control
 */
function resetAll() {
	var formObj=document.form;
	// button
	ComEnableObject(formObj.btn_save, false);
	rhq_ofc_cd.SetSelectCode(g_rhq_ofc_cd);
	ofc_cd.SetSelectCode(g_ofc_cd);
	formObj.sub_sys_cd.value = g_sub_sys_cd;
	sheetObjects[0].RemoveAll();
}

/** 
 * office code select box <br>
 * @param {IBMultiCombo} comboObj  
 * @param  {Array} arrStr
 */
function MakeComboObject(cmbObj, arrStr1, arrStr2) {
	var formObj = document.form;
	cmbObj.RemoveAll();
	var isExist = false;
	for (var i=1; i < arrStr1.length;i++ ) {
		var ar_hd_qtr_ofc_cd='';
		if (arrStr1[i] != '') {
			ar_hd_qtr_ofc_cd=arrStr1[i];
		}
		cmbObj.InsertItem(i-1, ar_hd_qtr_ofc_cd, ar_hd_qtr_ofc_cd);
		if(arrStr2 == ar_hd_qtr_ofc_cd) {
			isExist = true;
		}
	}
	if(formObj.usr_ofc_cd.value == "SINHO") {
		cmbObj.InsertItem(0, "SINHO", "SINHO");
		isExist = true;
	}
	if(isExist) {
		cmbObj.SetSelectCode(arrStr2);
		selOfcCd = arrStr2;
	} else {
		cmbObj.SetSelectCode(arrStr1[1]);
		selOfcCd = arrStr1[1];
	}
	cmbObj.SetSelectCode(selOfcCd);
}

//RHQ.Office 변경시, Office code 변경
function rhq_ofc_cd_OnChange()
{
	doActionIBSheet(sheetObjects[0], document.form, IBSEARCH_ASYNC02);
}
var selComboIndex, selComboCode;
function ofc_cd_OnSelect(comboObj, index, text, code) {
	selComboIndex = index;
	selComboCode = code;
}

function ofc_cd_OnCheckClick(comboObj) {
	ComSetMultiCombo(comboObj, selComboIndex, selComboCode);
} 